### ISSUE TITLE
salt-formula finish to fast

### ISSUE THREAD

**Issue by petersatsuse** [SUSE/saphanabootstrap-formula#116]
Running the formula as single task showed, that i still can not connect/login to the database after the salt call is finished, as the database is still starting up. 
It would be helpful to do something like a check if its accessible, before finishing the formula, especial in an fully automated workflow

**Comment by arbulu89** [comment]
Hi @petersatsuse ,
I would like to understand more about this issue.
As I understand you see that the database takes some additional time to start running completely after the installation state is over.
I have been testing this, and as soon as the installation state is done I can connect to the database properly.
I have added a test state after the installation that checks for the availability of the database, and it passes instantly.

In fact, I would say more. I have seen that the connectivity to the database is available even before the state is finished.

Could you provide additional logs and times about your case, so I can try to reproduce something similar.

**Comment by petersatsuse** [comment]
Need to rebuild the case - it was not in a cluster, i did a single node hana install. Let me re-check it.

**Comment by yeoldegrove** [comment]
@petersatsuse Please reopen if this is still an issue for you.
