### ISSUE TITLE
Azure: g_ip_{{ sid }}_HDB{{ instance }} is not moving together with SAP master

### ISSUE THREAD

**Issue by arbulu89** [SUSE/saphanabootstrap-formula#85]
In Azure, I have noticed that the resource agents group composed by socat and ip address it's not properly colocated with SAP master.
Most probably  due colocation value after we changed socat resource to `azure-lb`.
The official docs says 4000 of value, but we use 2000. 
We should change the template, test and fix the issue.

```
sudo crm configure primitive rsc_nc_HN1_HDB03 azure-lb port=62503 \
  meta resource-stickiness=0

sudo crm configure group g_ip_HN1_HDB03 rsc_ip_HN1_HDB03 rsc_nc_HN1_HDB03

sudo crm configure colocation col_saphana_ip_HN1_HDB03 4000: g_ip_HN1_HDB03:Started \
  msl_SAPHana_HN1_HDB03:Master  
```

https://docs.microsoft.com/en-us/azure/virtual-machines/workloads/sap/sap-hana-high-availability

**Comment by petersatsuse** [comment]
￼The change in the azure docu was done with commit f6bead3aae6e5b067ee113597a0cc57cdbaf46f2

https://github.com/MicrosoftDocs/azure-docs/commit/f6bead3aae6e5b067ee113597a0cc57cdbaf46f2#diff-7f4503b5f6a5f42ae8604f1cae7e2812

MSSedusch committed on May 7, 2018 Verified
1 parent 90522e5 commit f6bead3aae6e5b067ee113597a0cc57cdbaf46f2

It would be in general good idea to have a look at the MSFT github history what has changed over time, as it's a living document where fixes and new features get documented too.
As its all in github it should be easy to track

**Comment by arbulu89** [comment]
> ￼The change in the azure docu was done with commit f6bead3aae6e5b067ee113597a0cc57cdbaf46f2
> 
> [MicrosoftDocs/azure-docs@f6bead3#diff-7f4503b5f6a5f42ae8604f1cae7e2812](https://github.com/MicrosoftDocs/azure-docs/commit/f6bead3aae6e5b067ee113597a0cc57cdbaf46f2#diff-7f4503b5f6a5f42ae8604f1cae7e2812)
> 
> MSSedusch committed on May 7, 2018 Verified
> 1 parent 90522e5 commit f6bead3aae6e5b067ee113597a0cc57cdbaf46f2
> 
> It would be in general good idea to have a look at the MSFT github history what has changed over time, as it's a living document where fixes and new features get documented too.
> As its all in github it should be easy to track

Thanks @petersatsuse , I didn't even know that the documentation was stored in github.
And, yes we should closely look at the changes. Having a more direct communication would be great, to avoid just passive check of the updates hehe

**Comment by arbulu89** [comment]
@Simranpal @petersatsuse Confirmed. Using 4000 solves the location issue

**Comment by Simranpal** [comment]
https://github.com/SUSE/saphanabootstrap-formula/pull/86
